lib/modular_ui.dart, lib/src/buttons/loading_button.dart
=> created loading button

README.md, lib/modular_ui.dart, lib/src/buttons/gradient_block_level_button.dart, lib/src/buttons/gradient_button.dart, lib/src/buttons/loading_block_level_button.dart, lib/src/buttons/loading_button.dart, lib/src/buttons/outlined_block_level_button.dart, lib/src/buttons/outlined_button.dart, lib/src/buttons/primary_block_level_button.dart, lib/src/buttons/primary_button.dart, lib/src/buttons/text_block_level_button.dart, lib/src/buttons/text_button.dart
=> Created Buttons

README.md, lib/modular_ui.dart, lib/src/input_fields/primary_input_field.dart
=> created primary input field

README.md, lib/src/cards/sign_in_card.dart, lib/src/input_fields/primary_input_field.dart
=> created sign in card

.gitignore, example/.gitignore, example/lib/components/cards.dart, example/lib/home.dart, lib/modular_ui.dart, lib/src/cards/blog_card.dart, pubspec.yaml
Resolving Issue #17
Blog Card Preview
=> This  PR fixes Issue number #17

lib/modular_ui.dart, lib/src/breadcrumbs/breadcrumbs.dart
I implemented the breadcrumb component which you can see here in the tailwind docs: https://www.material-tailwind.com/docs/react/breadcrumbs#
Here is a preview on how it looks and how responsive it is:
https://github.com/opxica/modular-ui/assets/110409182/c52be62e-bfeb-4d14-a16a-53c780ed7d42
of course you can customize it how you like it.
=> Implemented Breadcrumbs

example/lib/components/switch.dart, example/lib/home.dart, lib/modular_ui.dart, lib/src/switch/switch.dart
=> Added switch

example/lib/components/avatar.dart, example/lib/home.dart, example/pubspec.yaml, lib/modular_ui.dart, lib/src/avatar/avatar.dart
Implemented Avatar component from the Shadcn Guidelines
https://ui.shadcn.com/docs/components/avatar
=> Implemented Avatar Component

example/lib/components/tabs.dart, example/lib/home.dart, lib/modular_ui.dart, lib/src/tabs/tabs.dart
I've now implemented the tabs component following the tailwind documentation.
https://www.material-tailwind.com/docs/react/tabs
This is how it looks:
https://github.com/opxica/modular-ui/assets/110409182/106806d2-ecf9-4061-8f14-2eae6e681ce1
=> Implemented Tabs component.

README.md, lib/src/buttons/gradient_button.dart, lib/src/buttons/loading_button.dart, lib/src/buttons/outlined_button.dart, lib/src/buttons/primary_button.dart, lib/src/buttons/text_button.dart, lib/src/cards/blog_card.dart, lib/src/cards/primary_card.dart, lib/src/cards/profile_card.dart, lib/src/cards/sign_in_card.dart, lib/src/cards/simple_card.dart
Added a maxwidth value to all the cards
Clamped the padding value of all buttons.
This PR Fixes #49
=> Added responsivness and breakpoints to required widgets

lib/src/buttons/gradient_block_level_button.dart, lib/src/buttons/gradient_button.dart, lib/src/buttons/loading_block_level_button.dart, lib/src/buttons/loading_button.dart, lib/src/buttons/outlined_block_level_button.dart, lib/src/buttons/outlined_button.dart, lib/src/buttons/primary_block_level_button.dart, lib/src/buttons/primary_button.dart, lib/src/buttons/text_block_level_button.dart, lib/src/buttons/text_button.dart, lib/src/cards/sign_in_card.dart
=> fix: Icon size in buttons

lib/src/buttons/gradient_button.dart, lib/src/buttons/loading_button.dart, lib/src/buttons/outlined_button.dart, lib/src/buttons/primary_button.dart, lib/src/buttons/text_button.dart, lib/src/cards/sign_in_card.dart
Added an optional field `maxHorizontalPadding` to clamp the horizontal Padding values.
=> fix: Buttons clamping

lib/src/buttons/loading_button.dart
=> fix:loading button

lib/modular_ui.dart, lib/src/buttons/loading_button.dart, lib/src/listtile/primary_listtile.dart
=> Implemented Primary Listitile

example/lib/components/switch.dart, example/lib/home.dart, lib/src/switch/switch.dart
Fixes Issue no #67 
https://github.com/opxica/modular-ui/assets/112308397/00ca712e-e280-418d-ace5-303dcc714f36
=> This PR Fixes Issue no 67

example/lib/components/cards.dart, example/lib/components/dialog.dart, lib/src/avatar/avatar.dart, lib/src/breadcrumbs/breadcrumbs.dart, lib/src/buttons/gradient_block_level_button.dart, lib/src/buttons/gradient_button.dart, lib/src/buttons/loading_block_level_button.dart, lib/src/buttons/loading_button.dart, lib/src/buttons/outlined_block_level_button.dart, lib/src/buttons/outlined_button.dart, lib/src/buttons/primary_block_level_button.dart, lib/src/buttons/primary_button.dart, lib/src/buttons/radio_button.dart, lib/src/buttons/text_block_level_button.dart, lib/src/buttons/text_button.dart, lib/src/cards/blog_card.dart, lib/src/cards/primary_card.dart, lib/src/cards/profile_card.dart, lib/src/cards/sign_in_card.dart, lib/src/cards/simple_card.dart, lib/src/checkbox/checkbox.dart, lib/src/dialog/primary_dialog.dart, lib/src/footers/logo_footer.dart, lib/src/footers/simple_footer.dart, lib/src/footers/sitemap_footer.dart, lib/src/input_fields/primary_input_field.dart, lib/src/switch/switch.dart, lib/src/tabs/tabs.dart
- Moves Constructors of package above the declaration for clear readability of properties of package.
- Provided Some variable and meaningful context to identify better.
- Fix Typos in comments and code.
Thanks!
=> [Refactored]: Package Components & Fix Typos

example/lib/components/buttons.dart, example/lib/widgets/custom_snackbar.dart, lib/enums/carousel_button_type.dart, lib/enums/carousel_indicator_type.dart, lib/modular_ui.dart, lib/src/carousel/carousel.dart, lib/src/carousel/components/indicator_dot.dart, lib/src/carousel/components/indicator_line.dart
- Separated `enums` in enums folder
- Exported `enums` to modular_ui.dart file
- Separated components in `components folder`
Thanks!
=> [Refactored]: Carousel in modular_ui

example/lib/components/slider.dart, example/lib/home.dart, lib/modular_ui.dart, lib/src/slider/components/custom_slider_thumb_shape.dart, lib/src/slider/slider.dart
Got the ui to optimum visuals but im having issues with functionality:{making the thumb move with the value}- would appreciate any help i can get
=> Implement_Slider#91

lib/modular_ui.dart, lib/src/buttons/secondary_block_level_button.dart, lib/src/buttons/secondary_button.dart
Create Secondary and Secondary Block Level Buttons just like shadcn.
This PR closes #88
=> Implemented Secondary Buttons

example/lib/components/dialog.dart, lib/src/dialog/primary_dialog.dart
Instead of taking too many parameters from the user. I have simplified it as :
The primary dialog can take up a list of action widgets in this list we can provide any flutter widget or any modular ui widget for example MUISecondaryButton. 
Added one more parameter to handle the main axis alignment of these action buttons.
This simplifies the code a lot.
=> fixed primary dialog

example/lib/components/avatar.dart, example/lib/components/cards.dart, example/lib/components/list_tile.dart, example/lib/components/rating_bar.dart, example/lib/components/slider.dart, example/lib/components/switch.dart, example/lib/home.dart, example/lib/widgets/custom_snackbar.dart, lib/constants/colors.dart, lib/constants/shadows.dart, lib/src/buttons/primary_button.dart, lib/src/buttons/secondary_button.dart, lib/src/cards/blog_card.dart, lib/src/cards/primary_card.dart, lib/src/cards/profile_card.dart, lib/src/cards/sign_in_card.dart, lib/src/cards/sign_up_card.dart, lib/src/carousel/components/indicator_dot.dart, lib/src/carousel/components/indicator_line.dart, lib/src/input_fields/primary_input_field.dart, lib/src/listtile/primary_listtile.dart, lib/src/slider/slider.dart, lib/src/utils/dimensions.dart, pubspec.yaml
- Updated `linter` version to latest version in `pubspec.yaml`.
- Migrated old `Key? key` syntax to `super.key`
- Created `colors.dart` & `shadows.dart` in `constants` folder to reusing shadows and colors.
- renamed the files `listtile.dart` => `list_tile.dart` & `ratingbar.dart` => `rating_bar.dart` just to keep linter happy in importing those files. Updated variables as the same.
- Moved Some `constructors` above the declarations.
- Changes default color of input field so that it is visible in `SignInCard` & `SignUpCard` mentioned in #111 
- Removed Spacing Issue of `SignInCard` & `SignUpCard` mentioned in #111 
- Spacing Issue in All the Card and made it PROD Ready
- Removed large comments while it explaining basic for loops etc. (Not Good Idea so translated to simplified comments)
- …
=> Fix Problems and Refactored Code, Made All cards prod ready, etc.

lib/src/input_fields/primary_input_field.dart
Added prefix icon and suffix icon as optional parameters to textfield also added prefixIconAction and suffixIconAction as optional parameters.
=> Add Prefix & Suffix Widget in TextField

README.md, example/lib/components/cards.dart, lib/src/cards/blog_card.dart, lib/src/cards/pricing_card.dart, lib/src/cards/primary_card.dart, lib/src/cards/profile_card.dart, lib/src/cards/sign_in_card.dart, lib/src/cards/sign_up_card.dart, lib/src/cards/simple_card.dart
=> Did some changes to cards : All the cards are production ready now.

example/lib/components/buttons.dart, example/lib/components/tabs.dart, example/lib/widgets/shadow.dart
added shadows to buttons in example app
=> add shadows to buttons

pubspec.yaml
=> yaml edited
